window.AI_MODELS_COMPARISON_DATA = {
  lastUpdated: "2026-08-27",
  sections: [
    {
      id: "website-design",
      title: "Website Design",
      subtitle: "UI / UX / Frontend",
      bestFor: ["GPT-5.2", "Gemini 3 Pro", "Claude Opus 4.5"],
      columns: [
        "Model",
        "UI Creativity",
        "Layout Variety",
        "Design Prompt Fidelity",
        "Frontend Code Quality",
        "Layout Repetition",
      ],
      rows: [
        ["GPT-5.2", "Very High", "Very High", "Very High", "High", "Very Rare"],
        ["GPT-5.1", "High", "High", "High", "High", "Sometimes"],
        ["GPT-5 mini", "Medium", "Medium", "Medium", "Medium", "Sometimes"],
        ["GPT-5 Codex", "Low", "Low", "Low", "Very High", "Often"],
        ["GPT-5.1 Codex", "Low", "Low", "Low", "Very High", "Often"],
        ["GPT-5.1 Codex Max", "Low", "Low", "Low", "Very High", "Very Often"],
        ["GPT-5.1 Codex Mini", "Medium", "Medium", "Medium", "High", "Often"],
        ["GPT-4.1", "High", "High", "High", "High", "Sometimes"],
        ["Gemini 3 Pro", "Very High", "Very High", "High", "High", "Very Rare"],
        ["Claude Opus 4.5", "Very High", "High", "Very High", "Very High", "Rare"],
        ["Claude Sonnet 4.5", "High", "High", "Very High", "Very High", "Rare"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Medium", "High", "Often"],
        ["Grok Code Fast 1", "Low", "Low", "Low", "High", "Often"],
        ["Raptor Mini", "Low", "Low", "Low", "Medium", "Often"],
      ],
    },
    {
      id: "game-design",
      title: "Game Design",
      subtitle: "Mechanics + Creativity",
      bestFor: ["GPT-5.2", "Claude Opus 4.5"],
      columns: ["Model", "Game Logic", "Creative Concepts", "System Balance", "Engine Support", "Notes"],
      rows: [
        ["GPT-5.2", "Very High", "Very High", "High", "Unity, Unreal, Web", "Best all-round"],
        ["GPT-5.1", "High", "High", "High", "Unity, Web", "Indie games"],
        ["GPT-5 mini", "Medium", "Medium", "Medium", "Web", "Simple games"],
        ["GPT-5 Codex", "Very High", "Low", "Very High", "Unity", "Logic-only"],
        ["GPT-5.1 Codex", "Very High", "Low", "Very High", "Unity", "Systems focus"],
        ["GPT-5.1 Codex Max", "Very High", "Low", "Very High", "Unity, Unreal", "Large systems"],
        ["GPT-5.1 Codex Mini", "High", "Medium", "High", "Unity", "Budget logic"],
        ["GPT-4.1", "High", "High", "High", "Unity, Web", "Stable design"],
        ["Gemini 3 Pro", "High", "Very High", "High", "Concept-heavy", "Creative focus"],
        ["Claude Opus 4.5", "Very High", "High", "Very High", "Unity, Unreal", "Deep mechanics"],
        ["Claude Sonnet 4.5", "Very High", "High", "Very High", "Unity, Unreal", "Reliable"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Medium", "Web", "Casual games"],
        ["Grok Code Fast 1", "High", "Low", "Medium", "Code-only", "Fast prototype"],
        ["Raptor Mini", "Medium", "Low", "Medium", "Code-only", "Simple logic"],
      ],
    },
    {
      id: "bug-fixing",
      title: "Bug Fixing & Debugging",
      subtitle: "Detection + Root Cause + Scale",
      bestFor: ["GPT-5.1 Codex Max", "Claude Sonnet 4.5", "Claude Opus 4.5"],
      columns: ["Model", "Bug Detection", "Root Cause Analysis", "Large Codebase", "Accuracy", "Speed"],
      rows: [
        ["GPT-5.2", "High", "High", "High", "High", "High"],
        ["GPT-5.1", "High", "High", "Medium", "High", "High"],
        ["GPT-5 mini", "Medium", "Medium", "Low", "Medium", "High"],
        ["GPT-5 Codex", "Very High", "Very High", "High", "Very High", "Medium"],
        ["GPT-5.1 Codex", "Very High", "Very High", "High", "Very High", "Medium"],
        ["GPT-5.1 Codex Max", "Very High", "Very High", "Very High", "Very High", "Medium"],
        ["GPT-5.1 Codex Mini", "High", "Medium", "Medium", "High", "High"],
        ["GPT-4.1", "High", "High", "Medium", "High", "High"],
        ["Gemini 3 Pro", "High", "High", "Medium", "High", "Medium"],
        ["Claude Opus 4.5", "Very High", "Very High", "High", "Very High", "Medium"],
        ["Claude Sonnet 4.5", "Very High", "Very High", "High", "Very High", "High"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Low", "Medium", "Very High"],
        ["Grok Code Fast 1", "High", "Medium", "Medium", "High", "Very High"],
        ["Raptor Mini", "Medium", "Medium", "Low", "Medium", "High"],
      ],
    },
    {
      id: "general-coding",
      title: "General Coding",
      subtitle: "Web / App / Backend",
      bestFor: ["Claude Sonnet 4.5", "Claude Opus 4.5", "GPT-5.1 Codex Max"],
      columns: ["Model", "Code Quality", "Multi-File Projects", "Refactoring", "Consistency"],
      rows: [
        ["GPT-5.2", "High", "High", "High", "High"],
        ["GPT-5.1", "High", "High", "High", "High"],
        ["GPT-5 mini", "Medium", "Medium", "Medium", "Medium"],
        ["GPT-5 Codex", "Very High", "High", "Very High", "Very High"],
        ["GPT-5.1 Codex", "Very High", "High", "Very High", "Very High"],
        ["GPT-5.1 Codex Max", "Very High", "Very High", "Very High", "Very High"],
        ["GPT-5.1 Codex Mini", "High", "Medium", "High", "High"],
        ["GPT-4.1", "High", "High", "High", "High"],
        ["Gemini 3 Pro", "High", "High", "Medium", "High"],
        ["Claude Opus 4.5", "Very High", "Very High", "Very High", "Very High"],
        ["Claude Sonnet 4.5", "Very High", "Very High", "Very High", "Very High"],
        ["Claude Haiku 4.5", "High", "Medium", "Medium", "High"],
        ["Grok Code Fast 1", "High", "Medium", "Medium", "High"],
        ["Raptor Mini", "Medium", "Low", "Medium", "Medium"],
      ],
    },
    {
      id: "creativity",
      title: "Creativity & Idea Generation",
      subtitle: "Originality + Visual Thinking",
      bestFor: ["GPT-5.2", "Gemini 3 Pro", "Claude Opus 4.5"],
      columns: ["Model", "Original Ideas", "Visual Thinking", "Avoids Repetition"],
      rows: [
        ["GPT-5.2", "Very High", "Very High", "Very High"],
        ["GPT-5.1", "High", "High", "Medium"],
        ["GPT-5 mini", "Medium", "Medium", "Medium"],
        ["GPT-5 Codex", "Low", "Low", "Low"],
        ["GPT-5.1 Codex", "Low", "Low", "Low"],
        ["GPT-5.1 Codex Max", "Low", "Low", "Low"],
        ["GPT-5.1 Codex Mini", "Medium", "Medium", "Medium"],
        ["GPT-4.1", "High", "High", "Medium"],
        ["Gemini 3 Pro", "Very High", "Very High", "Very High"],
        ["Claude Opus 4.5", "High", "High", "High"],
        ["Claude Sonnet 4.5", "High", "High", "High"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Medium"],
        ["Grok Code Fast 1", "Low", "Low", "Low"],
        ["Raptor Mini", "Low", "Low", "Low"],
      ],
    },
    {
      id: "speed-cost",
      title: "Speed & Cost",
      subtitle: "Throughput + Cost Efficiency",
      bestFor: ["Grok Code Fast 1", "Claude Haiku 4.5"],
      columns: ["Model", "Speed", "Cost Efficiency", "Best Use Case"],
      rows: [
        ["GPT-5.2", "High", "Medium", "High-quality UI"],
        ["GPT-5.1", "High", "Medium", "Balanced work"],
        ["GPT-5 mini", "High", "Very High", "Budget tasks"],
        ["GPT-5 Codex", "Medium", "Low", "Coding logic"],
        ["GPT-5.1 Codex", "Medium", "Low", "Advanced coding"],
        ["GPT-5.1 Codex Max", "Medium", "Low", "Large projects"],
        ["GPT-5.1 Codex Mini", "High", "Very High", "Cheap coding"],
        ["GPT-4.1", "High", "Medium", "General use"],
        ["Gemini 3 Pro", "Medium", "Medium", "Creative reasoning"],
        ["Claude Opus 4.5", "Medium", "Low", "Maximum quality"],
        ["Claude Sonnet 4.5", "High", "Medium", "Production code"],
        ["Claude Haiku 4.5", "Very High", "Very High", "Cheap assistants"],
        ["Grok Code Fast 1", "Very High", "High", "Rapid coding"],
        ["Raptor Mini", "High", "High", "Simple edits"],
      ],
    },
  ],
  overallBest: {
    columns: ["Task", "Best Model"],
    rows: [
      ["Website Design", "GPT-5.6 Sol / Gemini 3.7 Flash"],
      ["Game Design", "GPT-5.6 Sol / Claude Opus 5"],
      ["Bug Fixing", "GPT-5.6 Sol / Claude Fable 5"],
      ["Production Code", "GPT-5.6 Terra / Claude Sonnet 5"],
      ["Creative Concepts", "GPT-5.6 Sol / Gemini 3.7 Flash"],
      ["Speed & Cost", "GPT-5.6 Luna / Gemini 3.5 Flash-Lite"],
    ],
  },
  // Benchmark records are normalized separately so a model can retain multiple provider reports.
  // Each record uses: modelId or modelName, name, score, date, and source.
  benchmarks: [
    { modelId: "kimi-k3", name: "LiveBench overall", score: "79.2", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "qwen3.8-max", name: "LiveBench overall", score: "78.5", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "deepseek-v4-flash-vision-exp", name: "LiveBench overall", score: "76.8", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "qwen3.8-flash-next", name: "LiveBench overall", score: "76.2", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "glm-5.3", name: "LiveBench overall", score: "76.1", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "qwen3.8-27b", name: "LiveBench overall", score: "75.3", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "kimi-k2.6", name: "LiveBench overall", score: "70.5", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "minimax-m3", name: "LiveBench overall", score: "67.3", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "qwen3.6-27b", name: "LiveBench overall", score: "64.0", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "glm-5", name: "SWE-bench Verified", score: "72.80% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "deepseek-v3.2", name: "SWE-bench Verified", score: "70.00% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "kimi-k2-thinking", name: "SWE-bench Verified", score: "63.40% resolved", date: "2025-12-10", source: "https://www.swebench.com/" },
    { modelId: "minimax-m2", name: "SWE-bench Verified", score: "61.00% resolved", date: "2025-11-24", source: "https://www.swebench.com/" },
    { modelId: "qwen3-coder-480b", name: "SWE-bench Verified", score: "55.40% resolved", date: "2025-08-02", source: "https://www.swebench.com/" },
    { modelId: "glm-4.6", name: "SWE-bench Verified", score: "55.40% resolved", date: "2025-12-01", source: "https://www.swebench.com/" },
    { modelId: "glm-4.5", name: "SWE-bench Verified", score: "54.20% resolved", date: "2025-08-22", source: "https://www.swebench.com/" },
    { modelId: "kimi-k2-instruct", name: "SWE-bench Verified", score: "43.80% resolved", date: "2025-08-07", source: "https://www.swebench.com/" },
    { modelId: "qwen2.5-coder-32b", name: "SWE-bench Verified", score: "9.00% resolved", date: "2025-08-03", source: "https://www.swebench.com/" },
    { modelId: "gpt-5.6-sol", name: "LiveBench overall", score: "81.0", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gpt-5.6-terra", name: "LiveBench overall", score: "77.9", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gpt-5.6-luna", name: "LiveBench overall", score: "73.6", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "claude-fable-5", name: "LiveBench overall", score: "83.0", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "claude-opus-5", name: "LiveBench overall", score: "80.1", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "claude-sonnet-5", name: "LiveBench overall", score: "76.0", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gemini-3.7-flash", name: "LiveBench overall", score: "78.8", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gemini-3.6-flash", name: "LiveBench overall", score: "73.6", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gemini-3.5-flash", name: "LiveBench overall", score: "74.6", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gemini-3.5-flash-lite", name: "LiveBench overall", score: "63.9", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gemini-3.1-pro", name: "LiveBench overall", score: "77.0", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "grok-4.6", name: "LiveBench overall", score: "78.0", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "deepseek-v4-pro", name: "LiveBench overall", score: "77.4", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "deepseek-v4-flash", name: "LiveBench overall", score: "74.2", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "glm-5.2", name: "LiveBench overall", score: "73.2", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "gpt-5.2", name: "LiveBench overall", score: "74.6", date: "2026-06-25", source: "https://livebench.ai/" },
    { modelId: "claude-opus-4.5", name: "SWE-bench Verified", score: "76.80% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "claude-sonnet-4.5", name: "SWE-bench Verified", score: "71.40% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "claude-haiku-4.5", name: "SWE-bench Verified", score: "66.60% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "gemini-3-flash", name: "SWE-bench Verified", score: "75.80% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "gemini-2.5-flash", name: "SWE-bench Verified", score: "28.73% resolved", date: "2025-07-26", source: "https://www.swebench.com/" },
    { modelId: "gpt-4.1", name: "SWE-bench Verified", score: "39.58% resolved", date: "2025-07-26", source: "https://www.swebench.com/" },
    { modelId: "gpt-5.1-legacy", name: "SWE-bench Verified", score: "66.00% resolved", date: "2025-11-20", source: "https://www.swebench.com/" },
    { modelId: "gpt-5.1-codex-legacy", name: "SWE-bench Verified", score: "66.00% resolved", date: "2025-11-24", source: "https://www.swebench.com/" },
    { modelId: "kimi-k2.5", name: "SWE-bench Verified", score: "70.80% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "minimax-m2.5", name: "SWE-bench Verified", score: "75.80% resolved", date: "2026-02-17", source: "https://www.swebench.com/" },
    { modelId: "llama-4-maverick", name: "SWE-bench Verified", score: "21.04% resolved", date: "2025-07-20", source: "https://www.swebench.com/" },
  ],
  catalogLastVerified: "2026-08-27",
  modelCatalog: [
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", provider: "OpenAI", region: "United States", type: "Reasoning", modality: "Text, image", context: "1.05M", input: "$4 / 1M", output: "$20 / 1M", maxOutput: "128K", availability: "OpenAI API; region and tier limits apply", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026-08", api: "Responses API", source: "https://developers.openai.com/api/docs/models/gpt-5.6-sol", status: "Verified" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", provider: "OpenAI", region: "United States", type: "Reasoning", modality: "Text, image", context: "1.05M", input: "$2 / 1M", output: "$12 / 1M", maxOutput: "128K", availability: "OpenAI API; region and tier limits apply", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026-08", api: "Responses API", source: "https://developers.openai.com/api/docs/models/gpt-5.6-terra", status: "Verified" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", provider: "OpenAI", region: "United States", type: "Reasoning", modality: "Text, image", context: "1.05M", input: "$0.20 / 1M", output: "$1.20 / 1M", maxOutput: "128K", availability: "OpenAI API; region and tier limits apply", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026-08", api: "Responses API", source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna", status: "Verified" },
    { id: "claude-fable-5", name: "Claude Fable 5", provider: "Anthropic", region: "United States", type: "Reasoning", modality: "Text, image", context: "1M", input: "$10 / 1M", output: "$50 / 1M", maxOutput: "128K", availability: "Claude API and partner platforms; platform-specific availability varies", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026", api: "Anthropic API", source: "https://platform.claude.com/docs/en/docs/about-claude/models", status: "Verified" },
    { id: "claude-opus-5", name: "Claude Opus 5", provider: "Anthropic", region: "United States", type: "Reasoning", modality: "Text, image", context: "1M", input: "$5 / 1M", output: "$25 / 1M", maxOutput: "128K", availability: "Claude API and partner platforms; platform-specific availability varies", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026", api: "Anthropic API", source: "https://platform.claude.com/docs/en/docs/about-claude/models", status: "Verified" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", provider: "Anthropic", region: "United States", type: "General", modality: "Text, image", context: "1M", input: "$2 / 1M", output: "$10 / 1M", maxOutput: "128K", availability: "Claude API and partner platforms; platform-specific availability varies", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026", api: "Anthropic API", source: "https://platform.claude.com/docs/en/docs/about-claude/models", status: "Verified" },
    { id: "gpt-5.2", name: "GPT-5.2", provider: "OpenAI", region: "United States", type: "Reasoning", modality: "Text, image", context: "400K", input: "$1.75 / 1M", output: "$14 / 1M", maxOutput: "128K", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2025-12", api: "OpenAI API", source: "https://developers.openai.com/api/docs/models/gpt-5.2", status: "Verified" },
    { id: "gpt-4.1", name: "GPT-4.1", provider: "OpenAI", region: "United States", type: "General", modality: "Text, image", context: "1,047,576", input: "$2 / 1M", output: "$8 / 1M", maxOutput: "32,768", reasoning: false, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2025-04", api: "OpenAI API", source: "https://developers.openai.com/api/docs/models/gpt-4.1", status: "Verified" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5", provider: "Anthropic", region: "United States", type: "Reasoning", modality: "Text, image", context: "200K", input: "$5 / 1M", output: "$25 / 1M", maxOutput: "64K", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2025-11", api: "Anthropic API", source: "https://platform.claude.com/docs/en/models/opus-4-5/overview", status: "Verified" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", provider: "Anthropic", region: "United States", type: "General", modality: "Text, image", context: "200K", input: "$3 / 1M", output: "$15 / 1M", maxOutput: "64K", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2025-09", api: "Anthropic API", source: "https://platform.claude.com/docs/en/models/sonnet-4-5/overview", status: "Verified" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash", provider: "Google", region: "United States", type: "General", modality: "Text, image, audio, video", context: "1M", input: "$0.75 / 1M", output: "$3.75 / 1M", maxOutput: "Not listed on pricing page", availability: "Gemini API and AI Studio; available regions apply", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026-08", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/pricing", status: "Verified" },
    { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash", provider: "Google", region: "United States", type: "Fast", modality: "Text, image, audio, video", context: "1M", input: "$0.75 / 1M", output: "$3.75 / 1M", maxOutput: "Not listed on pricing page", availability: "Gemini API and AI Studio; available regions apply", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/pricing", status: "Verified" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", provider: "Google", region: "United States", type: "Fast", modality: "Text, image, audio, video", context: "1M", input: "$1.50 / 1M", output: "$9 / 1M", maxOutput: "Not listed on pricing page", availability: "Gemini API and AI Studio; available regions apply", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/pricing", status: "Verified" },
    { id: "gemini-3.5-flash-lite", name: "Gemini 3.5 Flash-Lite", provider: "Google", region: "United States", type: "Fast", modality: "Text, image, audio, video", context: "1M", input: "$0.30 / 1M", output: "$2.50 / 1M", maxOutput: "Not listed on pricing page", availability: "Gemini API and AI Studio; available regions apply", reasoning: false, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/pricing", status: "Verified" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", provider: "Google", region: "United States", type: "Reasoning", modality: "Text, image, audio, video, PDF", context: "1,048,576", input: "$2 / 1M (<=200K); $4 / 1M (>200K)", output: "$12 / 1M (<=200K); $18 / 1M (>200K)", maxOutput: "65,536", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026-02", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview", status: "Verified" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash", provider: "Google", region: "United States", type: "General", modality: "Text, image, audio, video, PDF", context: "1,048,576", input: "$0.50 / 1M", output: "$3 / 1M", maxOutput: "65,536", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2025-12", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/models/gemini-3-flash-preview", status: "Verified" },
    { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 Flash-Lite", provider: "Google", region: "United States", type: "Fast", modality: "Text, image, audio, video", context: "1,048,576", input: "$0.25 / 1M text/image/video; $0.50 / 1M audio", output: "$1.50 / 1M", maxOutput: "65,536", reasoning: false, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/pricing", status: "Verified" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", provider: "Google", region: "United States", type: "Reasoning", modality: "Text, image, audio, video", context: "1,048,576", input: "$0.30 / 1M text/image/video; $1 / 1M audio", output: "$2.50 / 1M", maxOutput: "65,536", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2025-03", api: "Gemini API", source: "https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash", status: "Verified" },
    { id: "grok-4.6", name: "Grok 4.6", provider: "xAI", region: "United States", type: "Reasoning", modality: "Text, image", context: "500K", input: "$2 / 1M", output: "$6 / 1M", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2026-02", api: "xAI API", source: "https://docs.x.ai/docs/models", status: "Verified" },
    { id: "deepseek-v4-pro", name: "DeepSeek-V4-Pro", provider: "DeepSeek", region: "China", type: "Reasoning", modality: "Text", context: "1M", input: "$0.22 / 1M off-peak; $0.44 peak", output: "$1.98 / 1M off-peak; $3.96 peak", maxOutput: "384K", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026-08", api: "DeepSeek API, Anthropic API", source: "https://api-docs.deepseek.com/quick_start/pricing/", status: "Verified" },
    { id: "deepseek-v4-flash", name: "DeepSeek-V4-Flash", provider: "DeepSeek", region: "China", type: "General", modality: "Text", context: "1M", input: "$0.007 / 1M off-peak; $0.014 peak", output: "$0.66 / 1M off-peak; $1.32 peak", maxOutput: "384K", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026-07", api: "DeepSeek API, Anthropic API", source: "https://api-docs.deepseek.com/quick_start/pricing/", status: "Verified" },
    { id: "qwen3-max", name: "Qwen3-Max", provider: "Alibaba / Qwen", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2025", api: "DashScope", source: "https://www.alibabacloud.com/help/en/model-studio/models", status: "Verify specs" },
    { id: "glm-5.2", name: "GLM-5.2", provider: "Zhipu AI / Z.ai", region: "China", type: "Reasoning", modality: "Text", context: "1M", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "BigModel API", source: "https://www.zhipuai.cn/en", status: "Verify pricing" },
    { id: "glm-5v-turbo", name: "GLM-5V-Turbo", provider: "Zhipu AI / Z.ai", region: "China", type: "Multimodal", modality: "Text, image", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Not disclosed", release: "2026", api: "BigModel API", source: "https://www.zhipuai.cn/en", status: "Verify specs" },
    { id: "kimi-k2.5", name: "Kimi K2.5", provider: "Moonshot AI / Kimi", region: "China", type: "General", modality: "Text, image", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "Kimi API", source: "https://platform.kimi.ai/docs/guide/start-using-kimi-api", status: "Verify specs" },
    { id: "minimax-m2.5", name: "MiniMax-M2.5", provider: "MiniMax", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "MiniMax API", source: "https://www.minimaxi.com/", status: "Verify specs" },
    { id: "mimo-v2-flash", name: "MiMo-V2-Flash", provider: "Xiaomi", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "Not disclosed", source: "https://github.com/XiaomiMiMo/MiMo", status: "Verify specs" },
    { id: "mistral-medium-3.5", name: "Mistral Medium 3.5", provider: "Mistral AI", region: "France / Europe", type: "General", modality: "Text, image", context: "256K", input: "$1.50 / 1M", output: "$7.50 / 1M", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Modified MIT", release: "2026-04", api: "Mistral API", source: "https://docs.mistral.ai/models/mistral-medium-3-5-26-04", status: "Verified" },
    { id: "mistral-small-4", name: "Mistral Small 4", provider: "Mistral AI", region: "France / Europe", type: "Reasoning", modality: "Text, image", context: "256K", input: "$0.15 / 1M", output: "$0.60 / 1M", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Apache 2.0", release: "2026-03", api: "Mistral API", source: "https://docs.mistral.ai/models/mistral-small-4-0-26-03", status: "Verified" },
    { id: "mistral-large-3", name: "Mistral Large 3", provider: "Mistral AI", region: "France / Europe", type: "General", modality: "Text, image", context: "256K", input: "$0.50 / 1M", output: "$1.50 / 1M", reasoning: false, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Apache 2.0", release: "2025-12", api: "Mistral API", source: "https://docs.mistral.ai/models/mistral-large-3-25-12", status: "Verified" },
    { id: "nemotron-4.1", name: "Llama Nemotron", provider: "NVIDIA", region: "United States", type: "General", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "NVIDIA Open Model", release: "2025", api: "NVIDIA NIM", source: "https://developer.nvidia.com/nim", status: "Verify specs" },
    { id: "command-a", name: "Command A", provider: "Cohere", region: "Canada", type: "General", modality: "Text", context: "256K", maxOutput: "8K", input: "Provider pricing varies by platform", output: "Provider pricing varies by platform", reasoning: false, coding: true, multimodal: false, tools: true, weights: "Closed", license: "Proprietary", release: "2025-03", api: "Cohere API", source: "https://docs.cohere.com/docs/models", status: "Verified" },
    { id: "falcon-h1", name: "Falcon-H1", provider: "TII / Falcon", region: "United Arab Emirates", type: "General", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: false, weights: "Open-weight", license: "Falcon License", release: "2025", api: "Self-hosted", source: "https://huggingface.co/tiiuae", status: "Verify specs" },
    { id: "llama-4-maverick", name: "Llama 4 Maverick", provider: "Meta", region: "United States", type: "General", modality: "Text, image", context: "1M", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Llama 4 License", release: "2025-04", api: "Partner APIs", source: "https://www.llama.com/llama-downloads/", status: "Verify pricing" },
    { id: "jamba-1.6", name: "Jamba 1.6", provider: "AI21 Labs", region: "Israel", type: "General", modality: "Text", context: "256K", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Apache 2.0", release: "2025-03", api: "AI21 API", source: "https://docs.ai21.com/reference/jamba-models", status: "Verify pricing" },
    { id: "databricks-dbrx", name: "DBRX instruct", provider: "Databricks", region: "United States", type: "General", modality: "Text", context: "32K", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: false, weights: "Open-weight", license: "DBRX License", release: "2024-03", api: "Self-hosted", source: "https://github.com/databricks/dbrx", status: "Legacy reference" },
    { id: "seed-2.0", name: "Seed 2.0", provider: "ByteDance", region: "China", type: "General", modality: "Text, image, video", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Not disclosed", release: "2026", api: "Not disclosed", source: "https://seed.bytedance.com/", status: "Verify specs" },
    { id: "hunyuan-turbos", name: "Hunyuan Turbo S", provider: "Tencent", region: "China", type: "General", modality: "Text, image", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2025", api: "Tencent Cloud", source: "https://hunyuan.tencent.com/", status: "Verify specs" },
    { id: "ernie-5.0", name: "ERNIE 5.0", provider: "Baidu", region: "China", type: "General", modality: "Text, image, audio, video", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Not disclosed", release: "2026", api: "千帆 / Qianfan", source: "https://cloud.baidu.com/product/wenxinworkshop", status: "Verify specs" },
    { id: "lfm-2.5", name: "LFM2.5", provider: "Liquid AI", region: "United States", type: "Fast", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: false, weights: "Open-weight", license: "Not disclosed", release: "2025", api: "Self-hosted", source: "https://www.liquid.ai/liquid-foundation-models", status: "Verify specs" },
    { id: "together-open-models", name: "Together open model catalog", provider: "Together AI", region: "United States", type: "Platform", modality: "Model-specific", context: "Model-specific", input: "Model-specific", output: "Model-specific", reasoning: false, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Model-specific", release: "Rolling", api: "Together API", source: "https://docs.together.ai/docs/serverless-models", status: "Catalog entry" },
    { id: "glm-5", name: "GLM-5", provider: "Zhipu AI / Z.ai", region: "China", type: "Reasoning", modality: "Text", context: "1M", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "BigModel API", source: "https://www.zhipuai.cn/en", status: "Verified" },
    { id: "glm-5.3", name: "GLM-5.3", provider: "Zhipu AI / Z.ai", region: "China", type: "Reasoning", modality: "Text", context: "1M", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "BigModel API", source: "https://www.zhipuai.cn/en", status: "Verified" },
    { id: "glm-4.6", name: "GLM-4.6", provider: "Zhipu AI / Z.ai", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2025-09", api: "BigModel API", source: "https://www.zhipuai.cn/en", status: "Verified" },
    { id: "glm-4.5", name: "GLM-4.5", provider: "Zhipu AI / Z.ai", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2025-07", api: "BigModel API", source: "https://www.zhipuai.cn/en", status: "Verified" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max", provider: "Alibaba / Qwen", region: "China", type: "Reasoning", modality: "Text", context: "1M", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "DashScope", source: "https://huggingface.co/Qwen", status: "Verified" },
    { id: "qwen3.8-flash-next", name: "Qwen3.8-Flash-Next", provider: "Alibaba / Qwen", region: "China", type: "Fast", modality: "Text, image", context: "256K", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "DashScope / self-hosted", source: "https://huggingface.co/Qwen/Qwen3.8-Flash-Next", status: "Verified" },
    { id: "qwen3.8-27b", name: "Qwen3.8 27B", provider: "Alibaba / Qwen", region: "China", type: "General", modality: "Text, image", context: "256K", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "Self-hosted", source: "https://huggingface.co/Qwen/Qwen3.8-27B", status: "Verified" },
    { id: "qwen3-coder-480b", name: "Qwen3-Coder 480B/A35B Instruct", provider: "Alibaba / Qwen", region: "China", type: "Coding", modality: "Text", context: "256K", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Apache 2.0", release: "2025-07", api: "Self-hosted", source: "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct", status: "Verified" },
    { id: "qwen3.6-27b", name: "Qwen3.6 27B", provider: "Alibaba / Qwen", region: "China", type: "General", modality: "Text", context: "262K", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "Self-hosted", source: "https://huggingface.co/Qwen", status: "Verified" },
    { id: "kimi-k3", name: "Kimi K3", provider: "Moonshot AI / Kimi", region: "China", type: "Reasoning", modality: "Text", context: "1.05M", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "Kimi API", source: "https://platform.kimi.ai/docs/guide/start-using-kimi-api", status: "Verified" },
    { id: "kimi-k2.6", name: "Kimi K2.6", provider: "Moonshot AI / Kimi", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "Kimi API", source: "https://platform.kimi.ai/docs/guide/start-using-kimi-api", status: "Verified" },
    { id: "kimi-k2-thinking", name: "Kimi K2 Thinking", provider: "Moonshot AI / Kimi", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2025-11", api: "Self-hosted", source: "https://huggingface.co/moonshotai/Kimi-K2-Thinking", status: "Verified" },
    { id: "kimi-k2-instruct", name: "Kimi K2 Instruct", provider: "Moonshot AI / Kimi", region: "China", type: "General", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Modified MIT", release: "2025-07", api: "Self-hosted", source: "https://huggingface.co/moonshotai/Kimi-K2-Instruct", status: "Verified" },
    { id: "minimax-m3", name: "MiniMax M3", provider: "MiniMax", region: "China", type: "Reasoning", modality: "Text", context: "1M", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "MiniMax API", source: "https://www.minimaxi.com/", status: "Verified" },
    { id: "minimax-m2", name: "MiniMax M2", provider: "MiniMax", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2025-11", api: "MiniMax API", source: "https://www.minimaxi.com/", status: "Verified" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2", provider: "DeepSeek", region: "China", type: "Reasoning", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2025", api: "DeepSeek API", source: "https://github.com/deepseek-ai", status: "Verified" },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp", provider: "DeepSeek", region: "China", type: "Multimodal", modality: "Text, image", context: "1M", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: true, tools: true, weights: "Open-weight", license: "Not disclosed", release: "2026", api: "DeepSeek API", source: "https://api-docs.deepseek.com/quick_start/pricing/", status: "Verified" },
    { id: "qwen2.5-coder-32b", name: "Qwen2.5-Coder 32B Instruct", provider: "Alibaba / Qwen", region: "China", type: "Coding", modality: "Text", context: "128K", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: false, weights: "Open-weight", license: "Apache 2.0", release: "2024-11", api: "Self-hosted", source: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct", status: "Verified" },
    { id: "dots-unknown", name: "Dots", provider: "Emerging lab", region: "Not disclosed", type: "Not disclosed", modality: "Not disclosed", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: false, multimodal: false, tools: false, weights: "Not disclosed", license: "Not disclosed", release: "Not disclosed", api: "Not disclosed", source: "https://huggingface.co/models?search=dots", status: "No reliable spec source" },
    { id: "laguna-unknown", name: "Laguna", provider: "Emerging lab", region: "Not disclosed", type: "Not disclosed", modality: "Not disclosed", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: false, multimodal: false, tools: false, weights: "Not disclosed", license: "Not disclosed", release: "Not disclosed", api: "Not disclosed", source: "https://huggingface.co/models?search=laguna", status: "No reliable spec source" },
    { id: "gpt-5.1-legacy", name: "GPT-5.1 (editorial rating)", aliases: ["GPT-5.1"], provider: "OpenAI", region: "United States", type: "Legacy rating", modality: "Not disclosed", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: false, weights: "Closed", license: "Proprietary", release: "2025-11", api: "Not disclosed", source: "https://developers.openai.com/api/docs/models", status: "Editorial-only entry" },
    { id: "gpt-5-codex-legacy", name: "GPT-5 Codex (editorial rating)", aliases: ["GPT-5 Codex"], provider: "OpenAI", region: "United States", type: "Legacy rating", modality: "Not disclosed", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: false, weights: "Closed", license: "Proprietary", release: "2025", api: "Not disclosed", source: "https://developers.openai.com/api/docs/models", status: "Editorial-only entry" },
    { id: "gpt-5.1-codex-legacy", name: "GPT-5.1 Codex (editorial rating)", aliases: ["GPT-5.1 Codex"], provider: "OpenAI", region: "United States", type: "Legacy rating", modality: "Not disclosed", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: false, weights: "Closed", license: "Proprietary", release: "2025", api: "Not disclosed", source: "https://developers.openai.com/api/docs/models", status: "Editorial-only entry" },
    { id: "gpt-5.1-codex-max-legacy", name: "GPT-5.1 Codex Max (editorial rating)", aliases: ["GPT-5.1 Codex Max"], provider: "OpenAI", region: "United States", type: "Legacy rating", modality: "Not disclosed", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: false, weights: "Closed", license: "Proprietary", release: "2025", api: "Not disclosed", source: "https://developers.openai.com/api/docs/models", status: "Editorial-only entry" },
    { id: "gpt-5.1-codex-mini-legacy", name: "GPT-5.1 Codex Mini (editorial rating)", aliases: ["GPT-5.1 Codex Mini"], provider: "OpenAI", region: "United States", type: "Legacy rating", modality: "Not disclosed", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: true, coding: true, multimodal: false, tools: false, weights: "Closed", license: "Proprietary", release: "2025", api: "Not disclosed", source: "https://developers.openai.com/api/docs/models", status: "Editorial-only entry" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", provider: "Anthropic", region: "United States", type: "Fast", modality: "Text, image", context: "200K", input: "$1 / 1M", output: "$5 / 1M", maxOutput: "64K", reasoning: false, coding: true, multimodal: true, tools: true, weights: "Closed", license: "Proprietary", release: "2025-10", api: "Anthropic API", source: "https://platform.claude.com/docs/en/models/haiku-4-5/overview", status: "Verified" },
    { id: "grok-code-fast-legacy", name: "Grok Code Fast 1 (editorial rating)", aliases: ["Grok Code Fast 1"], provider: "xAI", region: "United States", type: "Legacy rating", modality: "Text", context: "Not disclosed", input: "Not disclosed", output: "Not disclosed", reasoning: false, coding: true, multimodal: false, tools: true, weights: "Closed", license: "Proprietary", release: "2025", api: "Not disclosed", source: "https://docs.x.ai/docs/models", status: "Editorial-only entry" },
  ],
};
