window.AI_MODELS_COMPARISON_DATA = {
  lastUpdated: "2025-12-13",
  modelsIncluded: [
    "GPT-5.2 (Preview)",
    "GPT-5.1 (Preview)",
    "GPT-5 mini",
    "GPT-5 Codex (Preview)",
    "GPT-5.1 Codex (Preview)",
    "GPT-5.1 Codex Max (Preview)",
    "GPT-5.1 Codex Mini (Preview)",
    "GPT-4.1",
    "Gemini 3 Pro (Preview)",
    "Claude Opus 4.5 (Preview)",
    "Claude Sonnet 4.5",
    "Claude Haiku 4.5",
    "Grok Code Fast 1",
    "Raptor Mini (Preview)",
  ],
  sections: [
    {
      id: "website-design",
      title: "Website Design",
      subtitle: "UI / UX / Frontend",
      bestFor: ["GPT-5.2", "Gemini 3 Pro", "Claude Opus 4.5"],
      columns: [
        "Model",
        "UI Creativity",
        "Layout Variety",
        "Design Prompt Fidelity",
        "Frontend Code Quality",
        "Layout Repetition",
      ],
      rows: [
        ["GPT-5.2", "Very High", "Very High", "Very High", "High", "Very Rare"],
        ["GPT-5.1", "High", "High", "High", "High", "Sometimes"],
        ["GPT-5 mini", "Medium", "Medium", "Medium", "Medium", "Sometimes"],
        ["GPT-5 Codex", "Low", "Low", "Low", "Very High", "Often"],
        ["GPT-5.1 Codex", "Low", "Low", "Low", "Very High", "Often"],
        ["GPT-5.1 Codex Max", "Low", "Low", "Low", "Very High", "Very Often"],
        ["GPT-5.1 Codex Mini", "Medium", "Medium", "Medium", "High", "Often"],
        ["GPT-4.1", "High", "High", "High", "High", "Sometimes"],
        ["Gemini 3 Pro", "Very High", "Very High", "High", "High", "Very Rare"],
        ["Claude Opus 4.5", "Very High", "High", "Very High", "Very High", "Rare"],
        ["Claude Sonnet 4.5", "High", "High", "Very High", "Very High", "Rare"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Medium", "High", "Often"],
        ["Grok Code Fast 1", "Low", "Low", "Low", "High", "Often"],
        ["Raptor Mini", "Low", "Low", "Low", "Medium", "Often"],
      ],
    },
    {
      id: "game-design",
      title: "Game Design",
      subtitle: "Mechanics + Creativity",
      bestFor: ["GPT-5.2", "Claude Opus 4.5"],
      columns: ["Model", "Game Logic", "Creative Concepts", "System Balance", "Engine Support", "Notes"],
      rows: [
        ["GPT-5.2", "Very High", "Very High", "High", "Unity, Unreal, Web", "Best all-round"],
        ["GPT-5.1", "High", "High", "High", "Unity, Web", "Indie games"],
        ["GPT-5 mini", "Medium", "Medium", "Medium", "Web", "Simple games"],
        ["GPT-5 Codex", "Very High", "Low", "Very High", "Unity", "Logic-only"],
        ["GPT-5.1 Codex", "Very High", "Low", "Very High", "Unity", "Systems focus"],
        ["GPT-5.1 Codex Max", "Very High", "Low", "Very High", "Unity, Unreal", "Large systems"],
        ["GPT-5.1 Codex Mini", "High", "Medium", "High", "Unity", "Budget logic"],
        ["GPT-4.1", "High", "High", "High", "Unity, Web", "Stable design"],
        ["Gemini 3 Pro", "High", "Very High", "High", "Concept-heavy", "Creative focus"],
        ["Claude Opus 4.5", "Very High", "High", "Very High", "Unity, Unreal", "Deep mechanics"],
        ["Claude Sonnet 4.5", "Very High", "High", "Very High", "Unity, Unreal", "Reliable"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Medium", "Web", "Casual games"],
        ["Grok Code Fast 1", "High", "Low", "Medium", "Code-only", "Fast prototype"],
        ["Raptor Mini", "Medium", "Low", "Medium", "Code-only", "Simple logic"],
      ],
    },
    {
      id: "bug-fixing",
      title: "Bug Fixing & Debugging",
      subtitle: "Detection + Root Cause + Scale",
      bestFor: ["GPT-5.1 Codex Max", "Claude Sonnet 4.5", "Claude Opus 4.5"],
      columns: ["Model", "Bug Detection", "Root Cause Analysis", "Large Codebase", "Accuracy", "Speed"],
      rows: [
        ["GPT-5.2", "High", "High", "High", "High", "High"],
        ["GPT-5.1", "High", "High", "Medium", "High", "High"],
        ["GPT-5 mini", "Medium", "Medium", "Low", "Medium", "High"],
        ["GPT-5 Codex", "Very High", "Very High", "High", "Very High", "Medium"],
        ["GPT-5.1 Codex", "Very High", "Very High", "High", "Very High", "Medium"],
        ["GPT-5.1 Codex Max", "Very High", "Very High", "Very High", "Very High", "Medium"],
        ["GPT-5.1 Codex Mini", "High", "Medium", "Medium", "High", "High"],
        ["GPT-4.1", "High", "High", "Medium", "High", "High"],
        ["Gemini 3 Pro", "High", "High", "Medium", "High", "Medium"],
        ["Claude Opus 4.5", "Very High", "Very High", "High", "Very High", "Medium"],
        ["Claude Sonnet 4.5", "Very High", "Very High", "High", "Very High", "High"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Low", "Medium", "Very High"],
        ["Grok Code Fast 1", "High", "Medium", "Medium", "High", "Very High"],
        ["Raptor Mini", "Medium", "Medium", "Low", "Medium", "High"],
      ],
    },
    {
      id: "general-coding",
      title: "General Coding",
      subtitle: "Web / App / Backend",
      bestFor: ["Claude Sonnet 4.5", "Claude Opus 4.5", "GPT-5.1 Codex Max"],
      columns: ["Model", "Code Quality", "Multi-File Projects", "Refactoring", "Consistency"],
      rows: [
        ["GPT-5.2", "High", "High", "High", "High"],
        ["GPT-5.1", "High", "High", "High", "High"],
        ["GPT-5 mini", "Medium", "Medium", "Medium", "Medium"],
        ["GPT-5 Codex", "Very High", "High", "Very High", "Very High"],
        ["GPT-5.1 Codex", "Very High", "High", "Very High", "Very High"],
        ["GPT-5.1 Codex Max", "Very High", "Very High", "Very High", "Very High"],
        ["GPT-5.1 Codex Mini", "High", "Medium", "High", "High"],
        ["GPT-4.1", "High", "High", "High", "High"],
        ["Gemini 3 Pro", "High", "High", "Medium", "High"],
        ["Claude Opus 4.5", "Very High", "Very High", "Very High", "Very High"],
        ["Claude Sonnet 4.5", "Very High", "Very High", "Very High", "Very High"],
        ["Claude Haiku 4.5", "High", "Medium", "Medium", "High"],
        ["Grok Code Fast 1", "High", "Medium", "Medium", "High"],
        ["Raptor Mini", "Medium", "Low", "Medium", "Medium"],
      ],
    },
    {
      id: "creativity",
      title: "Creativity & Idea Generation",
      subtitle: "Originality + Visual Thinking",
      bestFor: ["GPT-5.2", "Gemini 3 Pro", "Claude Opus 4.5"],
      columns: ["Model", "Original Ideas", "Visual Thinking", "Avoids Repetition"],
      rows: [
        ["GPT-5.2", "Very High", "Very High", "Very High"],
        ["GPT-5.1", "High", "High", "Medium"],
        ["GPT-5 mini", "Medium", "Medium", "Medium"],
        ["GPT-5 Codex", "Low", "Low", "Low"],
        ["GPT-5.1 Codex", "Low", "Low", "Low"],
        ["GPT-5.1 Codex Max", "Low", "Low", "Low"],
        ["GPT-5.1 Codex Mini", "Medium", "Medium", "Medium"],
        ["GPT-4.1", "High", "High", "Medium"],
        ["Gemini 3 Pro", "Very High", "Very High", "Very High"],
        ["Claude Opus 4.5", "High", "High", "High"],
        ["Claude Sonnet 4.5", "High", "High", "High"],
        ["Claude Haiku 4.5", "Medium", "Medium", "Medium"],
        ["Grok Code Fast 1", "Low", "Low", "Low"],
        ["Raptor Mini", "Low", "Low", "Low"],
      ],
    },
    {
      id: "speed-cost",
      title: "Speed & Cost",
      subtitle: "Throughput + Cost Efficiency",
      bestFor: ["Grok Code Fast 1", "Claude Haiku 4.5"],
      columns: ["Model", "Speed", "Cost Efficiency", "Best Use Case"],
      rows: [
        ["GPT-5.2", "High", "Medium", "High-quality UI"],
        ["GPT-5.1", "High", "Medium", "Balanced work"],
        ["GPT-5 mini", "High", "Very High", "Budget tasks"],
        ["GPT-5 Codex", "Medium", "Low", "Coding logic"],
        ["GPT-5.1 Codex", "Medium", "Low", "Advanced coding"],
        ["GPT-5.1 Codex Max", "Medium", "Low", "Large projects"],
        ["GPT-5.1 Codex Mini", "High", "Very High", "Cheap coding"],
        ["GPT-4.1", "High", "Medium", "General use"],
        ["Gemini 3 Pro", "Medium", "Medium", "Creative reasoning"],
        ["Claude Opus 4.5", "Medium", "Low", "Maximum quality"],
        ["Claude Sonnet 4.5", "High", "Medium", "Production code"],
        ["Claude Haiku 4.5", "Very High", "Very High", "Cheap assistants"],
        ["Grok Code Fast 1", "Very High", "High", "Rapid coding"],
        ["Raptor Mini", "High", "High", "Simple edits"],
      ],
    },
  ],
  overallBest: {
    columns: ["Task", "Best Model"],
    rows: [
      ["Website Design", "GPT-5.2"],
      ["Game Design", "GPT-5.2 / Claude Opus 4.5"],
      ["Bug Fixing", "GPT-5.1 Codex Max"],
      ["Production Code", "Claude Sonnet 4.5"],
      ["Creative Concepts", "GPT-5.2 / Gemini 3 Pro"],
      ["Speed & Cost", "Grok Code Fast 1 / Claude Haiku 4.5"],
    ],
  },
};
